title = "Gaussian Splatting Pup"
description = "Official code for the paper \"PUP 3D-GS: Principled Uncertainty Pruning for 3D Gaussian Splatting\"."
url = "https://github.com/j-alex-hanson/gaussian-splatting-pup"
type = "gaussian_splatting"

[environment]
python_version = "3.10"
cuda = "11.8"
PYTHONNOUSERSITE = "1"
torch_version = "2.7.1"
torchvision_version = "0.22.1"

[installation]
shared_env = true
channels = ["pytorch", "nvidia", "conda-forge"]


# dependencies = [
#     "gxx_linux-64",
#     "gcc_linux-64",
#     "make",
#     "cmake",
#     "colmap",
# ]

pip_dependencies = [
    "plyfile",
    "tqdm",
    "argparse",
]

build_commands = [
    # "pip install torch==2.7.1 torchvision==0.22.1 --index-url https://download.pytorch.org/whl/cu118",
    "pip install 'opencv-python<4.10.0' 'faiss-gpu-cu11' 'numpy<2.0.0'",
    "pip install --no-build-isolation {{method_vendor_dir}}/gaussian_splatting_pup/submodules/diff-gaussian-rasterization",
    "pip install --no-build-isolation {{method_vendor_dir}}/gaussian_splatting_pup/submodules/simple-knn",
    "pip install --no-build-isolation {{method_vendor_dir}}/gaussian_splatting_pup/submodules/compress-diff-gaussian-rasterization",
    "pip install --no-build-isolation {{method_vendor_dir}}/gaussian_splatting_pup/submodules/rasterization_and_pup_fisher",

]

[[installation.git_repos]]
url = "https://github.com/j-alex-hanson/gaussian-splatting-pup"
branch = "main"
path = "gaussian_splatting_pup"
recursive = true

[validation]
validation_command = "python -c 'import sys; sys.path.append(\"vendor/gaussian_splatting_pup\"); print(\"1. Torch & CUDA\"); import torch; print(f\"   Torch: {torch.__version__}\"); print(f\"   CUDA Available: {torch.cuda.is_available()}\"); print(\"2. Custom Extensions\"); import diff_gaussian_rasterization; print(\"   diff_gaussian_rasterization OK\"); import simple_knn; print(\"   simple_knn OK\"); print(\"3. Repo Modules\"); import scene; import gaussian_renderer; print(\"   Scene/Renderer OK\"); print(\"VALIDATION COMPLETE\")'"

[execution]
command = """
    python {{method_vendor_dir}}/gaussian_splatting_pup/convert.py -s {{inputs.source_path}} --skip_matching &&
    python {{method_vendor_dir}}/gaussian_splatting_pup/train.py \
        -s {{inputs.source_path}} \
        --model_path {{outputs.trained_model_dir}} \
        --iterations {{kwargs.iterations}} \
        --data_device cpu
"""

[execution.inputs]
expected_input_images_folder = "input"
expected_colmap_folder = "distorted/sparse/0"
expected_db_folder = "distorted"


[execution.help]
help_command = "python {{method_vendor_dir}}/gaussian_splatting_pup/train.py --help"

[execution.outputs]
trained_model_dir = "{{step_output_dir}}"

# MODULAR_GS_SIGNATURE: 27ac100990c68037bdd9c19eb6e0ef8c685ecb7c11b62a307a1c470539f2b94c3011599ae52ff90c30abe4fa71a510b7c5a46317d466c85a787d11cd3cb81291
