title = "GSplat"
description = "Implementazione CUDA ultra-veloce di Gaussian Splatting sviluppata da Nerfstudio."
url = "https://github.com/nerfstudio-project/gsplat"
type = "gaussian_splatting"


[environment]
python_version = "3.10"
cuda = "11.8"
PYTHONNOUSERSITE = "1"
torch_version = "2.7.1"
torchvision_version = "0.22.1"

[installation]
shared_env = true
channels = ["pytorch", "nvidia", "conda-forge"]

dependencies = [
]

pip_dependencies = [
    "numpy<2.0.0",
    "tqdm",
    "typing_extensions",
    "tyro",
    "imageio",
    "scikit-learn",
    "lpips",
    "matplotlib",
    "tensorboard",
]

build_commands = [
    "pip install --no-build-isolation -r {{method_vendor_dir}}/gsplat/examples/requirements.txt",
    "pip install --no-build-isolation -e {{method_vendor_dir}}/gsplat",
]


[[installation.git_repos]]
url = "https://github.com/nerfstudio-project/gsplat"
branch = "main"
path = "gsplat"
recursive = true

[validation]
validation_command = "python -c 'import gsplat; print(f\"GSplat version: {gsplat.__version__}\"); import torch; print(f\"CUDA Available: {torch.cuda.is_available()}\")'"

[execution]
command = """python {{method_vendor_dir}}/gsplat/examples/simple_trainer.py mcmc \
--data-dir {{inputs.source_path}} \
--result-dir {{outputs.trained_model_dir}} \
--data-factor 1 \
--disable-viewer \
--save-ply \
--max-steps {{kwargs.get('iterations', 60000)}} \
--app-opt \
--antialiased
"""

[execution.inputs]
expected_input_images_folder = "images"
expected_colmap_folder = "sparse/0"
expected_db_folder = "."

[execution.help]
help_command = "python {{method_vendor_dir}}/gsplat/examples/simple_trainer.py mcmc --help"

[execution.outputs]
trained_model_dir = "{{step_output_dir}}"

# MODULAR_GS_SIGNATURE: a2e382c8f1f791793d7f43d4847adb40612a4f5232470c924591a41ab3d19056a66d25966208261e52cc90a1167c369617251bb0bdec8da04ca75c3105342df3
