title = "GSplat"
description = "Implementazione CUDA ultra-veloce di Gaussian Splatting sviluppata da Nerfstudio."
url = "https://github.com/nerfstudio-project/gsplat"
type = "gaussian_splatting"


[environment]
python_version = "3.10"
cuda = "11.8"
PYTHONNOUSERSITE = "1"
torch_version = "2.7.1"
torchvision_version = "0.22.1"

[installation]
shared_env = true
channels = ["pytorch", "nvidia", "conda-forge"]

# dependencies = [
#     "gxx_linux-64",
#     "gcc_linux-64",
#     "make",
#     "cmake",
#     "ninja",
#     "cuda-toolkit"
# ]

pip_dependencies = [
    "numpy<2.0.0",
    "tqdm",
    "typing_extensions",
    "tyro",
    "imageio",
    "scikit-learn",
    "lpips",
    "matplotlib",
    "tensorboard",
]

build_commands = [
    # "pip install torch==2.7.1 torchvision==0.22.1 --index-url https://download.pytorch.org/whl/cu118",
    "pip install --no-build-isolation -r {{method_vendor_dir}}/gsplat/examples/requirements.txt",
    "pip install --no-build-isolation -e {{method_vendor_dir}}/gsplat",
]


[[installation.git_repos]]
url = "https://github.com/nerfstudio-project/gsplat"
branch = "main"
path = "gsplat"
recursive = true

[validation]
validation_command = "python -c 'import gsplat; print(f\"GSplat version: {gsplat.__version__}\"); import torch; print(f\"CUDA Available: {torch.cuda.is_available()}\")'"

[execution]
command = """python {{method_vendor_dir}}/gsplat/examples/simple_trainer.py mcmc \
--data-dir {{inputs.source_path}} \
--result-dir {{outputs.trained_model_dir}} \
--data-factor 1 \
--disable-viewer \
--save-ply \
--max-steps {{kwargs.get('iterations', 60000)}} \
--random-bkgd \
--opacity-reg 0.025 \
--scale-reg 0.02 \
--strategy.min-opacity 0.015 \
--strategy.noise-lr 300000 \
--strategy.cap-max 600000 \
--app-opt \
--antialiased
"""

[execution.inputs]
expected_input_images_folder = "images"
expected_colmap_folder = "sparse/0"
expected_db_folder = "."

[execution.help]
help_command = "python {{method_vendor_dir}}/gsplat/examples/simple_trainer.py mcmc --help"

[execution.outputs]
trained_model_dir = "{{step_output_dir}}"