title = "Mip Splatting"
description = " Mip-Splatting: Alias-free 3D Gaussian Splatting "
url = "https://github.com/autonomousvision/mip-splatting"
type = "gaussian_splatting"

[global_options]
filter_opacity_threshold = 0.1

[environment]
python_version = "3.10"
cuda = "11.8"
PYTHONNOUSERSITE = "1"
torch_version = "2.7.1"
torchvision_version = "0.22.1"

[installation]
shared_env = true
channels = ["pytorch", "nvidia", "conda-forge"]


# dependencies = [
#     "gxx_linux-64",
#     "gcc_linux-64",
#     "make",
#     "cmake",
#     "colmap",
# ]

pip_dependencies = [
    "plyfile",
    "tqdm",
    "argparse",
    "open3d",
    "ninja",
    "GPUtil",
    "lpips",
]

build_commands = [
    # "pip install torch==2.7.1 torchvision==0.22.1 --index-url https://download.pytorch.org/whl/cu118",
    "pip install 'opencv-python<4.10.0' 'faiss-gpu-cu11' 'numpy<2.0.0'",
    "pip install --no-build-isolation {{method_vendor_dir}}/mip_splatting/submodules/diff-gaussian-rasterization",
    "pip install --no-build-isolation {{method_vendor_dir}}/mip_splatting/submodules/simple-knn",
]

[[installation.git_repos]]
url = "https://github.com/autonomousvision/mip-splatting"
branch = "main"
path = "mip_splatting"
recursive = true

[validation]
validation_command = "python -c 'import sys; sys.path.append(\"vendor/mip_splatting\"); print(\"1. Torch & CUDA\"); import torch; print(f\"   Torch: {torch.__version__}\"); print(f\"   CUDA Available: {torch.cuda.is_available()}\"); print(\"2. Custom Extensions\"); import diff_gaussian_rasterization; print(\"   diff_gaussian_rasterization OK\"); import simple_knn; print(\"   simple_knn OK\"); print(\"3. Repo Modules\"); import scene; import gaussian_renderer; print(\"   Scene/Renderer OK\"); print(\"VALIDATION COMPLETE\")'"

[execution]
command = "python {{method_vendor_dir}}/mip_splatting/convert.py -s {{inputs.source_path}} --skip_matching && python {{method_vendor_dir}}/mip_splatting/train.py -s {{inputs.source_path}} --model_path {{outputs.trained_model_dir}} --iterations {{kwargs.iterations}} --data_device cpu"

[execution.inputs]
expected_input_images_folder = "input"
expected_colmap_folder = "distorted/sparse/0"
expected_db_folder = "distorted"


[execution.help]
help_command = "python {{method_vendor_dir}}/mip_splatting/train.py --help"

[execution.outputs]
trained_model_dir = "{{step_output_dir}}"

# MODULAR_GS_SIGNATURE: 53e26a4cffa6415618d938202c00794d9f91187e84b07dcbb1769a61d3805009375fc63e5bf3d27a99b459df6223af4fb73350130a6ad6b68dfa0868c3b35413
