title = "Nerfstudio"
description = "State-of-the-art framework for NeRF and Splatting training."
url = "https://github.com/nerfstudio-project/nerfstudio"
type = "gaussian_splatting"



[environment]
python_version = "3.10"
cuda = "11.8"
# Isolamento forzato: impedisce a Python di caricare pacchetti da /home/ater/.local
# Questo è fondamentale perché vedo dai log che sta caricando sklearn/open3d da lì.
PYTHONNOUSERSITE = "1"

[installation]
channels = ["pytorch", "nvidia", "conda-forge"]

wheels_base_url = "https://huggingface.co/datasets/AterMors/gs_wheels/resolve/main"

dependencies = [
    # PyTorch con CUDA
    # "pytorch=2.1.2",
    # "torchvision=0.16.2",
    # "numpy<2.0.0",
]

pip_dependencies = [
    "nerfstudio",
    "plyfile",
    "tqdm",
    "@wheel:diff-gaussian-rasterization",
    "@wheel:tinycudann",
]

build_commands = [
    "pip install torch==2.1.2 torchvision==0.16.2 --index-url https://download.pytorch.org/whl/cu118",
    "pip install 'opencv-python<4.10.0' 'faiss-gpu-cu11' 'numpy<2.0.0'",
]

post_install_commands = [
    # "ns-install-cli",
]

[validation]
validation_command = "ns-train --help"

# MODULAR_GS_SIGNATURE: e0f9b82c0549bbc918ed18c8ce32ab95c45a36ce6ab4a8769a39ccbc12ccbd5a55236369f5d4940b83a125bb3e2c6da11f686dcd0596d0209e95acf51229c2f8
