title = "Nerfstudio"
description = "State-of-the-art framework for NeRF and Splatting training."
url = "https://github.com/nerfstudio-project/nerfstudio"
type = "gaussian_splatting"



[environment]
python_version = "3.10"
cuda = "11.8"
# Isolamento forzato: impedisce a Python di caricare pacchetti da /home/ater/.local
# Questo è fondamentale perché vedo dai log che sta caricando sklearn/open3d da lì.
PYTHONNOUSERSITE = "1"

[installation]
channels = ["pytorch", "nvidia", "conda-forge"]

wheels_base_url = "https://huggingface.co/datasets/AterMors/gs_wheels/resolve/main"

dependencies = [
    # PyTorch con CUDA
    # "pytorch=2.1.2",
    # "torchvision=0.16.2",
    # "numpy<2.0.0",
]

pip_dependencies = [
    "nerfstudio",
    "plyfile",
    "tqdm",
    "@wheel:diff-gaussian-rasterization",
    "@wheel:tinycudann",
]

build_commands = [
    "pip install torch==2.1.2 torchvision==0.16.2 --index-url https://download.pytorch.org/whl/cu118",
    "pip install 'opencv-python<4.10.0' 'faiss-gpu-cu11' 'numpy<2.0.0'",
]

post_install_commands = [
    # "ns-install-cli",
]

[validation]
validation_command = "ns-train --help"

# MODULAR_GS_SIGNATURE: fda0a8983d8638f1ed22d7d51449ed03270a513f506f3b4e0e63b3d9ca4f0c3df482877be8ec9674d6c8aee76e652912192152d1b31290f976d3a9091b31ed11
