title = "On_the_fly_nvs"
description = "On-the-fly Reconstruction for Large-Scale Novel View Synthesis from Unposed Images"
url = "https://github.com/graphdeco-inria/on-the-fly-nvs"

[environment]
python_version = "3.10"
cuda = "11.8"
PYTHONNOUSERSITE = "1"

[installation]
channels = ["pytorch", "nvidia", "conda-forge"]

dependencies = [
    "gxx_linux-64=11.*",
    "gcc_linux-64=11.*",
    "make",
    "cmake",
    "ninja",
    "glm",
    "colmap",
    "plyfile",
    "websockets",
    "glew",
    "glfw",
    "mesa-libgl-devel-cos7-x86_64",
    "mesa-libglu-devel-cos7-x86_64",
]

pip_dependencies = [
    "plyfile",
    "tqdm",
    "argparse",
    "setuptools",
    "wheel",
    "websockets",
    "cupy-cuda11x",
    "lpips",
    "hatchling",
    "scikit-build-core",
]

build_commands = [
    "pip install torch==2.7.1 torchvision==0.22.1 --index-url https://download.pytorch.org/whl/cu118",
    "pip install 'opencv-python<4.10.0' 'faiss-gpu-cu11' 'numpy<2.0.0'",
    "pip install --no-build-isolation {{method_vendor_dir}}/on_the_fly_nvs/submodules/diff-gaussian-rasterization",
    "pip install --no-build-isolation {{method_vendor_dir}}/on_the_fly_nvs/submodules/simple-knn",
    "pip install --no-build-isolation {{method_vendor_dir}}/on_the_fly_nvs/submodules/fused-ssim",
    # "pip install --no-build-isolation {{method_vendor_dir}}/on_the_fly_nvs/submodules/graphdecoviewer",
]


[[installation.git_repos]]
url = "https://github.com/graphdeco-inria/on-the-fly-nvs"
branch = "main"
path = "on_the_fly_nvs"
recursive = true

[validation]
validation_command = "python -c 'import sys; sys.path.append(\"vendor/on_the_fly_nvs\"); print(\"1. Torch & CUDA\"); import torch; print(f\"   Torch: {torch.__version__}\"); print(f\"   CUDA Available: {torch.cuda.is_available()}\"); print(\"2. Custom Extensions\"); import diff_gaussian_rasterization; print(\"   diff_gaussian_rasterization OK\"); import simple_knn; print(\"   simple_knn OK\"); import fused_ssim; print(\" fused_ssim OK\"); print(\"3. Repo Modules\"); import scene; import gaussian_renderer; print(\"   Scene/Renderer OK\"); print(\"VALIDATION COMPLETE\")'"

[execution]
#TODO: estrapolare la logica di esecuzione da root del vendor nei metodi core
command = "cd {{method_vendor_dir}}/on_the_fly_nvs && python {{method_vendor_dir}}/on_the_fly_nvs/train.py -s {{inputs.source_path}} --model_path {{outputs.trained_model_dir}} --use_colmap_poses"

[execution.inputs]
expected_input_images_folder = "images"
expected_colmap_folder = "sparse/0"
expected_db_folder = "sparse"


[execution.outputs]
trained_model_dir = "{{step_output_dir}}"

# MODULAR_GS_SIGNATURE: d5cbbc53ff66909c660b684715799dfc70a66f314833a7186b646373cef7b3e96b05c39dd6367ce26dcf2175a33371e258c25061ac9e292c265eb07218d876f5
