name: modular_GS
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  
  # Dipendenze della pipeline
  - typer     # Per la CLI
  - toml
  - tomli
  - tomli-w      # Per i file .toml
  - jinja2    # Per il templating dei comandi  
  - rerun-sdk
  - pyyaml