name: modular_GS
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - typer 
  - toml
  - tomli
  - tomli-w 
  - jinja2 
  - rerun-sdk
  - pyyaml
  - plyfile
  - numpy
  - pip:
    - opencv-python
    - streamlit