title = "COLMAP"
description = "General-purpose Structure-from-Motion (SfM) and Multi-View Stereo (MVS) pipeline."
url = "https://colmap.github.io/"
type = "sfm"

[environment]
python_version = "3.10"
cuda = "12.1"
PYTHONNOUSERSITE = "1"
torch_version = "2.1.2"
torchvision_version = "0.16.2"


[installation]
shared_env = false
channels = ["pytorch", "nvidia", "conda-forge"]

dependencies = [
    "colmap",
    "ffmpeg",
    "imagemagick",
    # "pytorch=2.1.2",
    # "torchvision=0.16.2",
    # "pytorch-cuda=11.8"
]

pip_dependencies = [
    "pycolmap",
    "opencv-python",
    "tqdm",
    "numpy",
    "scipy",
    "pandas",
    "plyfile"
]


build_commands = [
]

[validation]
validation_command = "colmap help"

# MODULAR_GS_SIGNATURE: 01c0d5c2c76d7f7b16a5aa5f4aeb6d305d08b124a0714c5ce59476716cfb45cf
