title = "COLMAP"
description = "General-purpose Structure-from-Motion (SfM) and Multi-View Stereo (MVS) pipeline."
url = "https://colmap.github.io/"
type = "sfm"

[environment]
python_version = "3.10"
cuda = "12.1"
PYTHONNOUSERSITE = "1"
torch_version = "2.1.2"
torchvision_version = "0.16.2"


[installation]
shared_env = false
channels = ["pytorch", "nvidia", "conda-forge"]

dependencies = [
    "colmap",
    "ffmpeg",
    "imagemagick",
    # "pytorch=2.1.2",
    # "torchvision=0.16.2",
    # "pytorch-cuda=11.8"
]

pip_dependencies = [
    "pycolmap",
    "opencv-python",
    "tqdm",
    "numpy",
    "scipy",
    "pandas",
    "plyfile"
]


build_commands = [
]

[validation]
validation_command = "colmap help"

# MODULAR_GS_SIGNATURE: d9fe647c1dc6379d271330c99436ef9a7a77e9f829445fa31ba9a39cf0865843b08a37ad78da0207ff794f9034610a39bfa1600ef9ab5c35343edda5df59bd5b
