title = "Images to Gaussian Splatting (MASt3R+FastGS)"
description = "Estrae frame nitidi, calcola SfM con MASt3R e allena Gaussian Splatting."

[global_options]
filter_opacity_threshold = 0.15

[[steps]]
name = "StructureFromMotion"
method = "methods/sfm/mast3r_sfm.toml"
[steps.inputs]
images_dir = "{{context.input_file}}"
[steps.kwargs]
scenegraph_type = "swin"

output_key = "sfm_ready_path"
primary_output = "model_dir"


[[steps]]
name = "Training"
method = "methods/splat/fastgs.toml"
[steps.inputs]
#{StepName}_{output_name}
source_path = "{{context.StructureFromMotion_model_dir}}"
[steps.kwargs]
iterations = 30000
densify_grad_threshold = 0.0002
grad_abs_thresh = 0.0012
grad_thresh = 0.0002
opacity_reset_interval = 3000
lambda_dsssim = 0.2
dense = 0.001
position_lr_final = 0.0000016
shfeature_lr = 0.005
feature_lr = 0.0025
loss_thresh = 0.1

# MODULAR_GS_SIGNATURE: bc845712be5e0720dd2d2cd5ae06eda901ed9a922cd56a2072d31e6a46a737297a50eb3a9c2129f38bede867097c90d83a1e3932c4514dacdd02e44cab3e9076