title = "Images to Gaussian Splatting (MASt3R)"
description = "Estrae frame nitidi, calcola SfM con MASt3R e allena Gaussian Splatting."

[global_options]
filter_opacity_threshold = 0.05


[[steps]]
name = "StructureFromMotion"
method = "methods/sfm/mast3r_sfm.toml"
[steps.inputs]
images_dir = "{{context.input_file}}"
[steps.kwargs]
scenegraph_type = "swin"
output_key = "sfm_ready_path"
primary_output = "model_dir"


[[steps]]
name = "Training"
method = "methods/splat/gsplat.toml"
[steps.inputs]
#{StepName}_{output_name}
source_path = "{{context.StructureFromMotion_model_dir}}"
[steps.kwargs]
iterations = 100000

# MODULAR_GS_SIGNATURE: ca53d5f93a27ee6482de38a412baddf43617257d5c3978f6fda0389085aaea6679afdef9c7a7100742a5987da41064daad097db0c7a60e4341ed071da5878206
