title = "Image to Gaussian Splatting (MASt3R)"
description = "Estrae frame nitidi, calcola SfM con MASt3R e allena Gaussian Splatting."



[[steps]]
name = "StructureFromMotion"
method = "methods/sfm/mast3r_sfm.toml"
[steps.inputs]
images_dir = "{{context.input_file}}"
[steps.kwargs]
scenegraph_type = "swin"
#chiave con cui salvare l'output nel contesto per il prossimo step
output_key = "sfm_ready_path"
primary_output = "model_dir"


[[steps]]
name = "Training"
method = "methods/splat/gaussian_splatting_graphdeco.toml"
[steps.inputs]
#{StepName}_{output_name}
source_path = "{{context.StructureFromMotion_model_dir}}"
[steps.kwargs]
iterations = 50000

# MODULAR_GS_SIGNATURE: b8487a379f9afff138e77d579cea6d341f4a403f16a7c39f90499d412b9f70462d97d5f804721f76d1fc901f5e86cb461091e84c7356d0c3dadb2afddb3fab88
