title = "Images to Gaussian Splatting (MASt3R)"
description = "Estrae frame nitidi, calcola SfM con MASt3R e allena Gaussian Splatting."

[global_options]
filter_opacity_threshold = 0.05


[[steps]]
name = "StructureFromMotion"
method = "methods/sfm/mast3r_sfm.toml"
[steps.inputs]
# Prende l'output dello step precedente
images_dir = "{{context.input_file}}"
[steps.kwargs]
scenegraph_type = "swin"
# Definiamo la chiave con cui salvare l'output nel contesto per il prossimo step
output_key = "sfm_ready_path"
primary_output = "model_dir"


[[steps]]
name = "Training"
method = "methods/splat/gsplat.toml"
[steps.inputs]
#{StepName}_{output_name}
source_path = "{{context.StructureFromMotion_model_dir}}"
[steps.kwargs]
iterations = 100000

# MODULAR_GS_SIGNATURE: b398a5794656943afd4bdbf63b05d607ba65c7f40b3167d116821176f9281c5fa64501386cb425c066affedf3f1a18bfc8f37ac685c557c0c859f3e4d50e47be
