title = "Images to Gaussian Splatting (MASt3R)"
description = "Estrae frame nitidi, calcola SfM con MASt3R e allena Gaussian Splatting."

[global_options]
filter_opacity_threshold = 0.05

[[steps]]
name = "StructureFromMotion"
method = "methods/sfm/mast3r_sfm.toml"
[steps.inputs]
images_dir = "{{context.input_file}}"
[steps.kwargs]
scenegraph_type = "swin"
output_key = "sfm_ready_path"
primary_output = "model_dir"


[[steps]]
name = "Training"
method = "methods/splat/taming_3dgs.toml"
[steps.inputs]
#{StepName}_{output_name}
source_path = "{{context.StructureFromMotion_model_dir}}"
[steps.kwargs]
iterations = 15000

# MODULAR_GS_SIGNATURE: 3e544196901b6ca67be73f425c15966967b14899d6326b8173fb1bef645692217152d93cbcf59e4ee2fc37dad7e353d914fd118d743df0a7c03c129cf52635bb
