title = "Image to Gaussian Splatting (MASt3R)"
description = "Estrae frame nitidi, calcola SfM con MASt3R e allena Gaussian Splatting."



[[steps]]
name = "StructureFromMotion"
method = "methods/sfm/mast3r_sfm.toml"
[steps.inputs]
images_dir = "{{context.input_file}}"
[steps.kwargs]
scenegraph_type = "swin"
#chiave con cui salvare l'output nel contesto per il prossimo step
output_key = "sfm_ready_path"
primary_output = "model_dir"


[[steps]]
name = "Training"
method = "methods/splat/faster_gs.toml"
[steps.inputs]
#{StepName}_{output_name}
source_path = "{{context.StructureFromMotion_model_dir}}"
[steps.kwargs]
iterations = 50000

# MODULAR_GS_SIGNATURE: 95148a8cc14c145d6c4c098639e8493a52ee190376d637b1eac0f3f05fc37e9350eb151b2d2e8f3558b75641642d0ec5d7db56bb33a787ee92af4deb09135185
