title = "Image to Gaussian Splatting (MASt3R)"
description = "Estrae frame nitidi, calcola SfM con MASt3R e allena Gaussian Splatting."



[[steps]]
name = "StructureFromMotion"
method = "methods/sfm/mast3r_sfm.toml"
[steps.inputs]
images_dir = "{{context.input_file}}"
[steps.kwargs]
scenegraph_type = "swin"
#chiave con cui salvare l'output nel contesto per il prossimo step
output_key = "sfm_ready_path"
primary_output = "model_dir"


[[steps]]
name = "Training"
method = "methods/splat/gaussian_splatting_graphdeco.toml"
[steps.inputs]
#{StepName}_{output_name}
source_path = "{{context.StructureFromMotion_model_dir}}"
[steps.kwargs]
iterations = 50000

# MODULAR_GS_SIGNATURE: 2b840d6d1a6ea5a6dc9ca3d87b319628ffcaa7cc57d9e45468f40c52b5d27206ee89485283594c9493dce8411723c28fd5d1c025e3f16e5bc8a0aa584027421b
