title = "Image to Gaussian Splatting (MASt3R)"
description = "Estrae frame nitidi, calcola SfM con MASt3R e allena Gaussian Splatting."



[[steps]]
name = "StructureFromMotion"
method = "methods/sfm/mast3r_sfm.toml"
[steps.inputs]
images_dir = "{{context.input_file}}"
[steps.kwargs]
scenegraph_type = "swin"
#chiave con cui salvare l'output nel contesto per il prossimo step
output_key = "sfm_ready_path"
primary_output = "model_dir"


[[steps]]
name = "Training"
method = "methods/splat/faster_gs.toml"
[steps.inputs]
#{StepName}_{output_name}
source_path = "{{context.StructureFromMotion_model_dir}}"
[steps.kwargs]
iterations = 50000

# MODULAR_GS_SIGNATURE: 4177938126b277e138aff2cf063f4fbd0e6ac0928a077433999b981acab31f71256322ef8c845002edd455e0b66d5d3fff1688ce58df9fe70ee52c0ccbff10b4
