title = "Video to Gaussian Splatting (MASt3R)"
description = "Estrae frame nitidi, calcola SfM con MASt3R e allena Gaussian Splatting."

[global_options]
filter_opacity_threshold = 0.15

[[steps]]
name = "Extraction"
method = "methods/preprocess/sharp_frames.toml"

[steps.inputs]
video = "{{context.input_file}}"
[steps.kwargs]
num_frames = 400


[[steps]]
name = "StructureFromMotion"
method = "methods/sfm/mast3r_sfm.toml"
[steps.inputs]
images_dir = "{{context.Extraction_sharp_images}}"
[steps.kwargs]
scenegraph_type = "swin"

output_key = "sfm_ready_path"
primary_output = "model_dir"


[[steps]]
name = "Training"
method = "methods/splat/fastgs.toml"
[steps.inputs]
#{StepName}_{output_name}
source_path = "{{context.StructureFromMotion_model_dir}}"
[steps.kwargs]
iterations = 30000
densify_grad_threshold = 0.0002
grad_abs_thresh = 0.0012
grad_thresh = 0.0002
opacity_reset_interval = 3000
lambda_dsssim = 0.2
dense = 0.001
position_lr_final = 0.0000016
shfeature_lr = 0.005
feature_lr = 0.0025
loss_thresh = 0.1

# MODULAR_GS_SIGNATURE: 3beb0765b7e607847ac90194dd2167288e82ef3d4ff93d5ebf22311e3400671d1515b311f93657de8a8f77720c42a07c52d007e8ef3e60454ef05fe24940c92a
