title = "Video to Gaussian Splatting (MASt3R)"
description = "Estrae frame nitidi, calcola SfM con MASt3R e allena Gaussian Splatting."

[global_options]
filter_opacity_threshold = 0.1

[[steps]]
name = "Extraction"
method = "methods/preprocess/sharp_frames.toml"
[steps.inputs]
video = "{{context.input_file}}"
[steps.kwargs]
num_frames = 400


[[steps]]
name = "StructureFromMotion"
method = "methods/sfm/mast3r_sfm.toml"
[steps.inputs]
images_dir = "{{context.Extraction_sharp_images}}"
[steps.kwargs]
scenegraph_type = "swin"
output_key = "sfm_ready_path"
primary_output = "model_dir"


[[steps]]
name = "Training"
method = "methods/splat/gaussian_splatting_pup.toml"
[steps.inputs]
#{StepName}_{output_name}
source_path = "{{context.StructureFromMotion_model_dir}}"
[steps.kwargs]
iterations = 30000

# MODULAR_GS_SIGNATURE: 17e03c311e2e49ae3c635a26700940d13155af1dffd25e927c9ff945190ee18c71b376b4991387f87ecb616a6c88d3d84eec91d3b508a1b4383e3a939ab9165a
