title = "Video to Gaussian Splatting (MASt3R)"
description = "Estrae frame nitidi, calcola SfM con MASt3R e allena Gaussian Splatting."

[global_options]
filter_opacity_threshold = 0.1

[[steps]]
name = "Extraction"
method = "methods/preprocess/sharp_frames.toml"
[steps.inputs]
video = "{{context.input_file}}"
[steps.kwargs]
num_frames = 400


[[steps]]
name = "StructureFromMotion"
method = "methods/sfm/mast3r_sfm.toml"
[steps.inputs]
images_dir = "{{context.Extraction_sharp_images}}"
[steps.kwargs]
scenegraph_type = "swin"
output_key = "sfm_ready_path"
primary_output = "model_dir"


[[steps]]
name = "Training"
method = "methods/splat/gaussian_splatting_pup.toml"
[steps.inputs]
#{StepName}_{output_name}
source_path = "{{context.StructureFromMotion_model_dir}}"
[steps.kwargs]
iterations = 30000

# MODULAR_GS_SIGNATURE: dbb4562a26e201109ab6453dabe6e9075b0419801f3b3a5050847b53bad4031b935420146d2d784d5220ed36ca1b3dc5b229d47383f7f428be4c9b0b8293e8e0
