title = "Video to Gaussian Splatting (MASt3R)"
description = "Estrae frame nitidi, calcola SfM con MASt3R e allena Gaussian Splatting."

[global_options]
filter_opacity_threshold = 0.1

[[steps]]
name = "Extraction"
method = "methods/preprocess/sharp_frames.toml"
# Questa chiave userà il valore passato via CLI --input
[steps.inputs]
video = "{{context.input_file}}"
[steps.kwargs]
num_frames = 400

[[steps]]
name = "StructureFromMotion"
method = "methods/sfm/mast3r_sfm.toml"
[steps.inputs]
# output step precedente
images_dir = "{{context.Extraction_sharp_images}}"
[steps.kwargs]
scenegraph_type = "swin"
# chiave con cui salvare l'output nel contesto per il prossimo step
output_key = "sfm_ready_path"
primary_output = "model_dir"


[[steps]]
name = "Training"
method = "methods/splat/2d_gaussian_splatting.toml"
[steps.inputs]
#{StepName}_{output_name}
source_path = "{{context.StructureFromMotion_model_dir}}"
[steps.kwargs]
iterations = 50000

# MODULAR_GS_SIGNATURE: 2d48d0ee1537dad9e03a8693230baffa41446da3b534be7f97d141e24db558f69856a31193ee5451b085a01d7955e6704825b19f169981df6d1edb998d61b49b
