title = "Video to Gaussian Splatting (MASt3R)"
description = "Estrae frame nitidi, calcola SfM con MASt3R e allena Gaussian Splatting."

[global_options]
filter_opacity_threshold = 0.1

[[steps]]
name = "Extraction"
method = "methods/preprocess/sharp_frames.toml"
# Questa chiave userà il valore passato via CLI --input
[steps.inputs]
video = "{{context.input_file}}"
[steps.kwargs]
num_frames = 400


[[steps]]
name = "StructureFromMotion"
method = "methods/sfm/mast3r_sfm.toml"
[steps.inputs]
# Prende l'output dello step precedente
images_dir = "{{context.Extraction_sharp_images}}"
[steps.kwargs]
scenegraph_type = "swin"
# Definiamo la chiave con cui salvare l'output nel contesto per il prossimo step
output_key = "sfm_ready_path"
primary_output = "model_dir"


[[steps]]
name = "Training"
method = "methods/splat/gaussian_splatting_pup.toml"
[steps.inputs]
#{StepName}_{output_name}
source_path = "{{context.StructureFromMotion_model_dir}}"
[steps.kwargs]
iterations = 30000

# MODULAR_GS_SIGNATURE: c4cf561fcae19bd4b59de8cdfa8a2c6a33c19b68ebf3a57588baa4f0bd5f4ff2f7709e8ead71673effd0143e077191b9d284aec6db82b9d54170961f7c715699
