title = "Video to Gaussian Splatting (MASt3R)"
description = "Estrae frame nitidi, calcola SfM con MASt3R e allena Gaussian Splatting."

[global_options]
filter_opacity_threshold = 0.1

[[steps]]
name = "Extraction"
method = "methods/preprocess/sharp_frames.toml"
[steps.inputs]
video = "{{context.input_file}}"
[steps.kwargs]
num_frames = 400


[[steps]]
name = "StructureFromMotion"
method = "methods/sfm/mast3r_sfm.toml"
[steps.inputs]
# Prende l'output dello step precedente
images_dir = "{{context.Extraction_sharp_images}}"
[steps.kwargs]
scenegraph_type = "swin"
# Definiamo la chiave con cui salvare l'output nel contesto per il prossimo step
output_key = "sfm_ready_path"
primary_output = "model_dir"


[[steps]]
name = "Training"
method = "methods/splat/on_the_fly_nvs.toml"
[steps.inputs]
#{StepName}_{output_name}
source_path = "{{context.StructureFromMotion_model_dir}}"
# [steps.kwargs]
# iterations = 15000

# MODULAR_GS_SIGNATURE: e12ba9df1ba99e6a53c451f6ab31d3dadf590443cec53f107c3663e9f56f57af8faf848f149351292f2b9d74386e28f6a446b5fd882da57f6b557bb03520f37f
