title = "Video to Gaussian Splatting (MASt3R)"
description = "Estrae frame nitidi, calcola SfM con MASt3R e allena Gaussian Splatting."

[[steps]]
name = "Extraction"
method = "methods/preprocess/sharp_frames.toml"
# Questa chiave userà il valore passato via CLI --input
[steps.inputs]
video = "{{context.input_file}}"
[steps.kwargs]
num_frames = 400


[[steps]]
name = "StructureFromMotion"
method = "methods/sfm/mast3r_sfm.toml"
[steps.inputs]
# Prende l'output dello step precedente
images_dir = "{{context.Extraction_sharp_images}}"
[steps.kwargs]
scenegraph_type = "swin"
# Definiamo la chiave con cui salvare l'output nel contesto per il prossimo step
output_key = "sfm_ready_path"
primary_output = "model_dir"


[[steps]]
name = "Training"
method = "methods/splat/gaussian_splatting_graphdeco.toml"
[steps.inputs]
#{StepName}_{output_name}
source_path = "{{context.StructureFromMotion_model_dir}}"
[steps.kwargs]
iterations = 50000

# MODULAR_GS_SIGNATURE: 53ee9d19b144ad9506b6442b8d2b1371730920e8812d84916e1a9d2390523806f5d0dd2b021c1677bc2e7e0b7906b0ea389a34e2faf402eb2183537912113ca1
