title = "Sharp Frames"
description = "Python tool to extract sharp frames from videos or image directories."
url = "https://github.com/Reflct/sharp-frames-python"
type = "preprocess"

[environment]
python_version = "3.11"
cuda = "11.8"
PYTHONNOUSERSITE = "1"

[installation]
share_env = false
channels = ["pytorch", "nvidia", "conda-forge"]

dependencies = [
    "ffmpeg=6.1.2",
    "x264", 
    "openh264",

]

pip_dependencies = [
    "sharp-frames",
]


[validation]
validation_command = "sharp-frames --help"

[execution]
command = "sharp-frames {{inputs.video}} {{outputs.sharp_images}} --selection-method best-n --num-frames {{kwargs.num_frames}} --min-buffer 3"

[execution.outputs]
sharp_images = "{{step_output_dir}}/images"

# MODULAR_GS_SIGNATURE: 8b77a4326e2c46d650e5176b98449554a1d2759552e09e6285f3f73634cadc918c5dced48ea5f90b1feb2b584e90c8ccd96c6fee9ad0b22055bfce947c0e17f0
