title = "Sharp Frames"
description = "Python tool to extract sharp frames from videos or image directories."
url = "https://github.com/Reflct/sharp-frames-python"
type = "preprocess"

[environment]
python_version = "3.11"
cuda = "11.8"
PYTHONNOUSERSITE = "1"

[installation]
share_env = false
channels = ["pytorch", "nvidia", "conda-forge"]

dependencies = [
    "ffmpeg=6.1.2",
    "x264", 
    "openh264",

]

pip_dependencies = [
    "sharp-frames",
]


[validation]
validation_command = "sharp-frames --help"

[execution]
command = "sharp-frames {{inputs.video}} {{outputs.sharp_images}} --selection-method best-n --num-frames {{kwargs.num_frames}} --min-buffer 3"

[execution.outputs]
sharp_images = "{{step_output_dir}}/images"

# MODULAR_GS_SIGNATURE: accdd29ff41a0a507271b94b1108b804b30440ce9e407cf22ae1d7aa9baa93dfe787ae55ff31081535701474cf6a149bce1eea1ae83d9af0f5dec011f6508501
